stages:
  - build
  - deploy


build:test:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
      when: always
  before_script:
    - echo "$CI_BUILD_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - cat "$ENV_FILE_TEST" > .env
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:test" . || { echo 'Build failed'; exit 1; }


build:prod:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
  before_script:
    - echo "$CI_BUILD_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - cat "$ENV_FILE_PROD" > .env
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:latest" . || { echo 'Build failed'; exit 1; }


deploy:test:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
      when: on_success
  before_script:
    - echo "$CI_BUILD_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
  script:
    - docker push "$CI_REGISTRY_IMAGE:test"
    - apk update && apk add openssh-client
    - chmod 600 $ID_RSA
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP -p 228 "
      docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY &&
      docker pull $CI_REGISTRY_IMAGE:test &&
      cd /home/super/test/app &&
      docker compose up -d test-frontend
      " || { echo 'Deploy failed'; exit 1; }


deploy:prod:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: on_success
  before_script:
    - echo "$CI_BUILD_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
  script:
    - docker push "$CI_REGISTRY_IMAGE:latest"
    - apk update && apk add openssh-client
    - chmod 600 $ID_RSA
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP -p 228 "
      docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY &&
      docker pull $CI_REGISTRY_IMAGE:latest &&
      cd /home/super/prod/app_web &&
      docker compose up -d frontend
      " || { echo 'Deploy failed'; exit 1; }
