export const USE_CASES = [
    "Tinder Photo",
    "Bali Influencer",
    "Cosplay",
    "Dating Photoshoot",
    "AI Action Figure",
    "Korean Profile Photo",
    "Glamour",
    "Lingerie",
    "Digital Nomad",
    "E-Girl",
    "Avatar AI",
    "AI Tattoo Generator",
    "Life on Mars",
    "Latex",
    "Cyberpunk Boudoir",
    "AI Influencer Generator",
    "LinkedIn Headshots",
    "Dubai Influencer",
    "AI Dating",
    "Boudoir",
    "Cyberpunk",
    "Old Money",
    "Rap Album Cover",
    "AI Yearbook",
    "OnlyFans",
    "AI Anime Character Creator",
    "Y2K Aesthetic",
    "Mob Wife",
    "Neon Tokyo",
    "AI Girlfriend",
]